[package]
name = "catlang"
version = "0.1.0"
authors = ["Alic Szecsei <aszecsei@gmail.com>"]
publish = false
description = "A compiler for the Catlang programming language"
documentation = "aszecsei.github.io/catlang"
repository = "github.com/aszecsei/catlang"

readme = "README.md"

keywords = ["catlang", "compiler"]

license = "MIT"
edition = "2018"

[dependencies]
chrono = "0.4.11"
clap = "2.33.0"
console = "0.10.0"
fnv = "1.0.6"
human-panic = "1.0.3"
indicatif = "0.14.0"
log = "0.4.8"
petgraph = "0.5.0"
serde = "1.0.106"
serde_derive = "1.0.106"
serde_yaml = "0.8.11"
logos = "0.11.0"
lazy_static = "1.4.0"
toolshed = "0.8.1"

[lib]
name = "catlang"
path = "src/lib/lib.rs"

[[bin]]
name = "catlang"
path = "src/bin/main.rs"
