version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/rust:latest
    working_directory: ~/catlang
    steps:
      - checkout
      - run:
          name: Install rustfmt
          command: rustup component add rustfmt-preview
      - restore_cache:
          keys:
            - rust-mod-v1-{{ checksum "Cargo.lock" }}
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt --all -- --check
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - run:
          name: Upload Coverage
          command: ./scripts/codecov.sh
      - save_cache:
          key: rust-mod-v1-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
