version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11.1
    working_directory: ~/catlang
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go run mage.go test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build