version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11.1
    working_directory: ~/catlang
    steps:

      - checkout
      - restore_cache:
        keys:
          - go-mod-v1-{{ checksum "go.sum" }}
      - run: go run mage.go test
      - save_cache:
        key: go-mod-v1-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build