on:
  pull_request:
  push:
    branches:
      - main

name: Check and Lint

env:
  LLVM_SYS_140_PREFIX: ./llvm

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Cache LLVM and Clang
        uses: actions/cache@v2
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-14.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.6.0
        with:
          version: "14.0"
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Cache LLVM and Clang
        uses: actions/cache@v2
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-14.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.6.0
        with:
          version: "14.0"
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Cache LLVM and Clang
        uses: actions/cache@v2
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-14.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.6.0
        with:
          version: "14.0"
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output