on:
  pull_request:
  push:
    branches:
      - main

name: Test with Code Coverage

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache LLVM and Clang
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-14.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.6.0
        with:
          version: "14.0"
      - run: echo "LLVM_SYS_140_PREFIX=${{ env.LLVM_PATH }}" >> $GITHUB_ENV

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: cobertura.xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml